swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: User Accounts API
      description: API for fetching All User's Accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Accounts data retrieved successully
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                ammount:
                  type: integer
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account:
    post:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: User Accounts API
      description: API for fetching One user account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: account's ID
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              date:
                type: string
                description: date of the day
      produces:
        - application/json
      responses:
        '200':
          description: Account data for last 30 days retrieved successully
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: id of the transaction
                ammount:
                  type: integer
                  description: ammount of the transction
                date:
                  type: string
                  description: date of the transaction
                place:
                  type: string
                  description: where you made the transaction
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        '200':
          description: Transaction data retrieved successuly
          schema:
            type: object
            properties:
              id:
                type: integer
                description: id of the transaction
              ammount:
                type: integer
                description: ammount of the transction
              date:
                type: string
                description: date of the transaction
              place:
                type: string
                description: where you made the transaction
              reason:
                type: string
                description: reason of the transaction
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      sercurity:
        - Bearer: []
      tags:
        - Accounts
      summary: User Profile API
      description: API to modify a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction attributes
          requiered: true
          schema:
            type: object
            properties:
              reason:
                type: string
                description: reason of the transaction
      responses:
        '200':
          description: Transaction data updated successuly
          schema:
            type: object
            properties:
              id:
                type: integer
                description: id of the transaction
              ammount:
                type: integer
                description: ammount of the transction
              date:
                type: string
                description: date of the transaction
              place:
                type: string
                description: where you made the transaction
              reason:
                type: string
                description: new reason of the transaction
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
